dist: trusty

services:
  - docker 

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD"  "$DOCKER_USERNAME" 
      - docker images
    - stage: deploy
      script:
      - eval "$(ssh-agent -s)"
      - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
      - ssh $SSH_USER@$1_DEPLOY_SERVER_IP "$DEPLOY_COMMAND"
      - ssh-agent -k
