version: 2
jobs:
  build_docker_image:
    machine: true
    steps:
      - checkout
      - run:
          name: Greeting
          command: docker build --help

      - run:
          name: Print the Current Time
          command: date
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "touch test_`date +%F`"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_docker_image
      - deploy:
          requires:
            - build_docker_image
          filters:
            branches:
              only: master
